#if !defined(__CINT__) || defined(__MAKECINT__)
#include "AnalysisMethods/PlotUtils/interface/PlotStuff.h"
#endif

//root -b -q "../CMSSW_7_4_7/src/AnalysisMethods/macros/QGTagging/plotQGValidation.C+"
void plotQGValidation( const TString inputdir="trees/150906_withHTprescales"
                     , const TString outputdir="plots"
                     , const TString format = "png"
                     )
{
  gSystem->mkdir(outputdir, true);
  TString lumi = "0.040*";
  TString wtVar = "weight*puWeightC"; // weight purwt
  bool scaleToData = true;
  TString dijetselection = "passDijet && passDijet3 && ht>450";

  PlotStuff* zjetPlots = new PlotStuff("plotQGValidationZjet.conf", inputdir, outputdir, 0, true);
  zjetPlots->setPlotSource(PlotStuff::TREES);
  zjetPlots->setPlotType(PlotStuff::DATAMC);
  zjetPlots->setTree("Events");
  zjetPlots->setFormat(format);
  zjetPlots->setWgtVar(lumi+wtVar);
  //zjetPlots->setWgtVar(lumi+"weight*puWeight");
  zjetPlots->setDataName("data_doublemu");
  //zjetPlots->setDataName("dyjetstoll"); zjetPlots->setDataIsMC();
  zjetPlots->setHeaderText("#sqrt{s} = 13 TeV", "X fb^{-1}", "");
  zjetPlots->setScaleToData(scaleToData);
  zjetPlots->setPlotOverflow(true);
  zjetPlots->setRatioPlot(true);

  PlotStuff* dijetPlots = new PlotStuff("plotQGValidationDijet.conf", inputdir, outputdir);
  dijetPlots->setPlotSource(PlotStuff::TREES);
  dijetPlots->setPlotType(PlotStuff::DATAMC);
  dijetPlots->setTree("Events");
  dijetPlots->setFormat(format);
  dijetPlots->setWgtVar(lumi+wtVar);
  dijetPlots->setDataName("data_jetht");
  dijetPlots->setHeaderText("#sqrt{s} = 13 TeV", "X fb^{-1}", "");
  dijetPlots->setScaleToData(scaleToData);
  dijetPlots->setPlotOverflow(true);
  dijetPlots->setRatioPlot(true);
  dijetPlots->setUnprescale(true);
  dijetPlots->setUnprescaleVar("prescale");
  //dijetPlots->setLogy();
  //dijetPlots->setMinLogScale(100);

  PlotStuff* gjetPlots = new PlotStuff("plotQGValidationGjet.conf", inputdir, outputdir);
  gjetPlots->setPlotSource(PlotStuff::TREES);
  gjetPlots->setPlotType(PlotStuff::DATAMC);
  gjetPlots->setTree("Events");
  gjetPlots->setFormat(format);
  gjetPlots->setWgtVar(lumi+wtVar);
  gjetPlots->setDataName("data_singlegm");
  //gjetPlots->setDataName("gjets"); gjetPlots->setDataIsMC();
  gjetPlots->setHeaderText("#sqrt{s} = 13 TeV", "X fb^{-1}", "");
  gjetPlots->setScaleToData(scaleToData);
  gjetPlots->setPlotOverflow(true);
  gjetPlots->setRatioPlot(true);

  zjetPlots->setColor("dyjetstoll_pu"    ,12);
  zjetPlots->setColor("dyjetstoll_undef" ,11);
  zjetPlots->setColor("dyjetstoll_charm" , 3);
  zjetPlots->setColor("dyjetstoll_bot"   , 7);
  zjetPlots->setColor("dyjetstoll_gluons", 2);
  zjetPlots->setColor("dyjetstoll_quarks", 4);
  dijetPlots->setColor("qcd_pu"    ,12);
  dijetPlots->setColor("qcd_undef" ,11);
  dijetPlots->setColor("qcd_charm" , 3);
  dijetPlots->setColor("qcd_bot"   , 7);
  dijetPlots->setColor("qcd_gluons", 2);
  dijetPlots->setColor("qcd_quarks", 4);
  gjetPlots->setColor("gjets_pu"    ,12);
  gjetPlots->setColor("gjets_undef" ,11);
  gjetPlots->setColor("gjets_charm" , 3);
  gjetPlots->setColor("gjets_bot"   , 7);
  gjetPlots->setColor("gjets_gluons", 2);
  gjetPlots->setColor("gjets_quarks", 4);

  TString central = " && abs(j0eta)<2.4";
  TString forward = " && abs(j0eta)>3.0 && abs(j0eta)<5.0";
  TString ptlow = " && j0pt>030";
  TString pt020 = " && j0pt>020 && j0pt<030";
  TString pt030 = " && j0pt>030 && j0pt<040";
  TString pt040 = " && j0pt>040 && j0pt<060";
  TString pt060 = " && j0pt>060 && j0pt<080";
  TString pt080 = " && j0pt>080 && j0pt<120";
  TString pt120 = " && j0pt>120 && j0pt<200";
  TString pt200 = " && j0pt>200 && j0pt<600";

  zjetPlots->addTreeVar("zjets_dilepmass"      , "dilepmass" , "passZjet && passZmass"+ptlow, "dilepmass"         , 30,  60, 120 );
  zjetPlots->addTreeVar("zjets_dilepmassNoCut" , "dilepmass" , "passZjet"             +ptlow, "dilepmass (no cut)", 30,  60, 120 );
  zjetPlots->addTreeVar("zjets_mu0pt"          , "mu0pt"     , "passZjet && passZmass"+ptlow, "mu0pt"             , 30,   0, 150 );
  zjetPlots->addTreeVar("zjets_mu1pt"          , "mu1pt"     , "passZjet && passZmass"+ptlow, "mu1pt"             , 30,   0, 150 );
  zjetPlots->addTreeVar("zjets_mu0eta"         , "mu0eta"    , "passZjet && passZmass"+ptlow, "mu0eta"            , 30,  -5,   5 );
  zjetPlots->addTreeVar("zjets_mu1eta"         , "mu1eta"    , "passZjet && passZmass"+ptlow, "mu1eta"            , 30,  -5,   5 );

  zjetPlots->addTreeVar("zjets_j0pt"      , "j0pt" , "passZjet && passZmass"+ptlow     , "pt_{T} [GeV]", 30,  0, 120 );
  zjetPlots->addTreeVar("zjets_j0eta"     , "j0eta", "passZjet && passZmass"+ptlow     , "#eta"        , 30, -5,   5 );
  zjetPlots->addTreeVar("zjets_j0eta_pt20", "j0eta", "passZjet && passZmass"+pt020     , "#eta (pt20-30)" , 30, -5,   5 );
  zjetPlots->addTreeVar("zjets_rho"       , "rho"  , "passZjet && passZmass"+ptlow     , "#rho"        , 30,  0,  30 );
  zjetPlots->addTreeVar("zjets_npv"       , "npv"  , "passZjet && passZmass"+ptlow     , "npv"         , 34,  1,  35 );
  zjetPlots->addTreeVar("zjets_j0pdgid" , "j0pdgid", "passZjet && passZmass"+ptlow     , "j0pdgid"     , 30,  -5,   5 );
  zjetPlots->addTreeVar("zjets_central_j0mult"   , "j0mult", "passZjet && passZmass"+central+ptlow, "multiplicity", 25, 0, 50 );
//zjetPlots->addTreeVar("zjets_central020_j0mult", "j0mult", "passZjet && passZmass"+central+pt020, "multiplicity", 25, 0, 50 );
  zjetPlots->addTreeVar("zjets_central030_j0mult", "j0mult", "passZjet && passZmass"+central+pt030, "multiplicity", 25, 0, 50 );
  zjetPlots->addTreeVar("zjets_central040_j0mult", "j0mult", "passZjet && passZmass"+central+pt040, "multiplicity", 25, 0, 50 );
  zjetPlots->addTreeVar("zjets_central060_j0mult", "j0mult", "passZjet && passZmass"+central+pt060, "multiplicity", 25, 0, 50 );
  zjetPlots->addTreeVar("zjets_central080_j0mult", "j0mult", "passZjet && passZmass"+central+pt080, "multiplicity", 25, 0, 50 );
  zjetPlots->addTreeVar("zjets_central120_j0mult", "j0mult", "passZjet && passZmass"+central+pt120, "multiplicity", 25, 0, 50 );
  zjetPlots->addTreeVar("zjets_central200_j0mult", "j0mult", "passZjet && passZmass"+central+pt200, "multiplicity", 25, 0, 50 );
  zjetPlots->addTreeVar("zjets_forward_j0mult"   , "j0mult", "passZjet && passZmass"+forward+ptlow, "multiplicity", 25, 0, 50 );
//zjetPlots->addTreeVar("zjets_forward020_j0mult", "j0mult", "passZjet && passZmass"+forward+pt020, "multiplicity", 25, 0, 50 );
//zjetPlots->addTreeVar("zjets_forward030_j0mult", "j0mult", "passZjet && passZmass"+forward+pt030, "multiplicity", 25, 0, 50 );
//zjetPlots->addTreeVar("zjets_forward040_j0mult", "j0mult", "passZjet && passZmass"+forward+pt040, "multiplicity", 25, 0, 50 );
//zjetPlots->addTreeVar("zjets_forward060_j0mult", "j0mult", "passZjet && passZmass"+forward+pt060, "multiplicity", 25, 0, 50 );
//zjetPlots->addTreeVar("zjets_forward080_j0mult", "j0mult", "passZjet && passZmass"+forward+pt080, "multiplicity", 25, 0, 50 );
//zjetPlots->addTreeVar("zjets_forward120_j0mult", "j0mult", "passZjet && passZmass"+forward+pt120, "multiplicity", 25, 0, 50 );
//zjetPlots->addTreeVar("zjets_forward200_j0mult", "j0mult", "passZjet && passZmass"+forward+pt200, "multiplicity", 25, 0, 50 );
  zjetPlots->addTreeVar("zjets_central_j0ptd"   , "j0ptd", "passZjet && passZmass"+central+ptlow, "ptD", 30, 0, 1 );
//zjetPlots->addTreeVar("zjets_central020_j0ptd", "j0ptd", "passZjet && passZmass"+central+pt020, "ptD", 30, 0, 1 );
  zjetPlots->addTreeVar("zjets_central030_j0ptd", "j0ptd", "passZjet && passZmass"+central+pt030, "ptD", 30, 0, 1 );
  zjetPlots->addTreeVar("zjets_central040_j0ptd", "j0ptd", "passZjet && passZmass"+central+pt040, "ptD", 30, 0, 1 );
  zjetPlots->addTreeVar("zjets_central060_j0ptd", "j0ptd", "passZjet && passZmass"+central+pt060, "ptD", 30, 0, 1 );
  zjetPlots->addTreeVar("zjets_central080_j0ptd", "j0ptd", "passZjet && passZmass"+central+pt080, "ptD", 30, 0, 1 );
  zjetPlots->addTreeVar("zjets_central120_j0ptd", "j0ptd", "passZjet && passZmass"+central+pt120, "ptD", 30, 0, 1 );
  zjetPlots->addTreeVar("zjets_central200_j0ptd", "j0ptd", "passZjet && passZmass"+central+pt200, "ptD", 30, 0, 1 );
  zjetPlots->addTreeVar("zjets_forward_j0ptd"   , "j0ptd", "passZjet && passZmass"+forward+ptlow, "ptD", 30, 0, 1 );
//zjetPlots->addTreeVar("zjets_forward020_j0ptd", "j0ptd", "passZjet && passZmass"+forward+pt020, "ptD", 30, 0, 1 );
//zjetPlots->addTreeVar("zjets_forward030_j0ptd", "j0ptd", "passZjet && passZmass"+forward+pt030, "ptD", 30, 0, 1 );
//zjetPlots->addTreeVar("zjets_forward040_j0ptd", "j0ptd", "passZjet && passZmass"+forward+pt040, "ptD", 30, 0, 1 );
//zjetPlots->addTreeVar("zjets_forward060_j0ptd", "j0ptd", "passZjet && passZmass"+forward+pt060, "ptD", 30, 0, 1 );
//zjetPlots->addTreeVar("zjets_forward080_j0ptd", "j0ptd", "passZjet && passZmass"+forward+pt080, "ptD", 30, 0, 1 );
//zjetPlots->addTreeVar("zjets_forward120_j0ptd", "j0ptd", "passZjet && passZmass"+forward+pt120, "ptD", 30, 0, 1 );
//zjetPlots->addTreeVar("zjets_forward200_j0ptd", "j0ptd", "passZjet && passZmass"+forward+pt200, "ptD", 30, 0, 1 );
  zjetPlots->addTreeVar("zjets_central_j0axis1"   , "j0axis1", "passZjet && passZmass"+central+ptlow, "-Log(axis_{1})", 40, 0, 10 );
//zjetPlots->addTreeVar("zjets_central020_j0axis1", "j0axis1", "passZjet && passZmass"+central+pt020, "-Log(axis_{1})", 40, 0, 10 );
  zjetPlots->addTreeVar("zjets_central030_j0axis1", "j0axis1", "passZjet && passZmass"+central+pt030, "-Log(axis_{1})", 40, 0, 10 );
  zjetPlots->addTreeVar("zjets_central040_j0axis1", "j0axis1", "passZjet && passZmass"+central+pt040, "-Log(axis_{1})", 40, 0, 10 );
  zjetPlots->addTreeVar("zjets_central060_j0axis1", "j0axis1", "passZjet && passZmass"+central+pt060, "-Log(axis_{1})", 40, 0, 10 );
  zjetPlots->addTreeVar("zjets_central080_j0axis1", "j0axis1", "passZjet && passZmass"+central+pt080, "-Log(axis_{1})", 40, 0, 10 );
  zjetPlots->addTreeVar("zjets_central120_j0axis1", "j0axis1", "passZjet && passZmass"+central+pt120, "-Log(axis_{1})", 40, 0, 10 );
  zjetPlots->addTreeVar("zjets_central200_j0axis1", "j0axis1", "passZjet && passZmass"+central+pt200, "-Log(axis_{1})", 40, 0, 10 );
  zjetPlots->addTreeVar("zjets_forward_j0axis1"   , "j0axis1", "passZjet && passZmass"+forward+ptlow, "-Log(axis_{1})", 40, 0, 10 );
//zjetPlots->addTreeVar("zjets_forward020_j0axis1", "j0axis1", "passZjet && passZmass"+forward+pt020, "-Log(axis_{1})", 40, 0, 10 );
//zjetPlots->addTreeVar("zjets_forward030_j0axis1", "j0axis1", "passZjet && passZmass"+forward+pt030, "-Log(axis_{1})", 40, 0, 10 );
//zjetPlots->addTreeVar("zjets_forward040_j0axis1", "j0axis1", "passZjet && passZmass"+forward+pt040, "-Log(axis_{1})", 40, 0, 10 );
//zjetPlots->addTreeVar("zjets_forward060_j0axis1", "j0axis1", "passZjet && passZmass"+forward+pt060, "-Log(axis_{1})", 40, 0, 10 );
//zjetPlots->addTreeVar("zjets_forward080_j0axis1", "j0axis1", "passZjet && passZmass"+forward+pt080, "-Log(axis_{1})", 40, 0, 10 );
//zjetPlots->addTreeVar("zjets_forward120_j0axis1", "j0axis1", "passZjet && passZmass"+forward+pt120, "-Log(axis_{1})", 40, 0, 10 );
//zjetPlots->addTreeVar("zjets_forward200_j0axis1", "j0axis1", "passZjet && passZmass"+forward+pt200, "-Log(axis_{1})", 40, 0, 10 );
  zjetPlots->addTreeVar("zjets_central_j0axis2"   , "j0axis1", "passZjet && passZmass"+central+ptlow, "-Log(axis_{2})", 40, 0, 10 );
//zjetPlots->addTreeVar("zjets_central020_j0axis2", "j0axis1", "passZjet && passZmass"+central+pt020, "-Log(axis_{2})", 40, 0, 10 );
  zjetPlots->addTreeVar("zjets_central030_j0axis2", "j0axis1", "passZjet && passZmass"+central+pt030, "-Log(axis_{2})", 40, 0, 10 );
  zjetPlots->addTreeVar("zjets_central040_j0axis2", "j0axis1", "passZjet && passZmass"+central+pt040, "-Log(axis_{2})", 40, 0, 10 );
  zjetPlots->addTreeVar("zjets_central060_j0axis2", "j0axis1", "passZjet && passZmass"+central+pt060, "-Log(axis_{2})", 40, 0, 10 );
  zjetPlots->addTreeVar("zjets_central080_j0axis2", "j0axis1", "passZjet && passZmass"+central+pt080, "-Log(axis_{2})", 40, 0, 10 );
  zjetPlots->addTreeVar("zjets_central120_j0axis2", "j0axis1", "passZjet && passZmass"+central+pt120, "-Log(axis_{2})", 40, 0, 10 );
  zjetPlots->addTreeVar("zjets_central200_j0axis2", "j0axis1", "passZjet && passZmass"+central+pt200, "-Log(axis_{2})", 40, 0, 10 );
  zjetPlots->addTreeVar("zjets_forward_j0axis2"   , "j0axis1", "passZjet && passZmass"+forward+ptlow, "-Log(axis_{2})", 40, 0, 10 );
//zjetPlots->addTreeVar("zjets_forward020_j0axis2", "j0axis1", "passZjet && passZmass"+forward+pt020, "-Log(axis_{2})", 40, 0, 10 );
//zjetPlots->addTreeVar("zjets_forward030_j0axis2", "j0axis1", "passZjet && passZmass"+forward+pt030, "-Log(axis_{2})", 40, 0, 10 );
//zjetPlots->addTreeVar("zjets_forward040_j0axis2", "j0axis1", "passZjet && passZmass"+forward+pt040, "-Log(axis_{2})", 40, 0, 10 );
//zjetPlots->addTreeVar("zjets_forward060_j0axis2", "j0axis1", "passZjet && passZmass"+forward+pt060, "-Log(axis_{2})", 40, 0, 10 );
//zjetPlots->addTreeVar("zjets_forward080_j0axis2", "j0axis1", "passZjet && passZmass"+forward+pt080, "-Log(axis_{2})", 40, 0, 10 );
//zjetPlots->addTreeVar("zjets_forward120_j0axis2", "j0axis1", "passZjet && passZmass"+forward+pt120, "-Log(axis_{2})", 40, 0, 10 );
//zjetPlots->addTreeVar("zjets_forward200_j0axis2", "j0axis1", "passZjet && passZmass"+forward+pt200, "-Log(axis_{2})", 40, 0, 10 );
  zjetPlots->addTreeVar("zjets_central_j0qgl"   , "j0qgl", "passZjet && passZmass"+central+ptlow, "QGL", 30, 0, 1 );
//zjetPlots->addTreeVar("zjets_central020_j0qgl", "j0qgl", "passZjet && passZmass"+central+pt020, "QGL", 30, 0, 1 );
  zjetPlots->addTreeVar("zjets_central030_j0qgl", "j0qgl", "passZjet && passZmass"+central+pt030, "QGL", 30, 0, 1 );
  zjetPlots->addTreeVar("zjets_central040_j0qgl", "j0qgl", "passZjet && passZmass"+central+pt040, "QGL", 30, 0, 1 );
  zjetPlots->addTreeVar("zjets_central060_j0qgl", "j0qgl", "passZjet && passZmass"+central+pt060, "QGL", 30, 0, 1 );
  zjetPlots->addTreeVar("zjets_central080_j0qgl", "j0qgl", "passZjet && passZmass"+central+pt080, "QGL", 30, 0, 1 );
  zjetPlots->addTreeVar("zjets_central120_j0qgl", "j0qgl", "passZjet && passZmass"+central+pt120, "QGL", 30, 0, 1 );
  zjetPlots->addTreeVar("zjets_central200_j0qgl", "j0qgl", "passZjet && passZmass"+central+pt200, "QGL", 30, 0, 1 );
  zjetPlots->addTreeVar("zjets_forward_j0qgl"   , "j0qgl", "passZjet && passZmass"+forward+ptlow, "QGL", 30, 0, 1 );
//zjetPlots->addTreeVar("zjets_forward020_j0qgl", "j0qgl", "passZjet && passZmass"+forward+pt020, "QGL", 30, 0, 1 );
//zjetPlots->addTreeVar("zjets_forward030_j0qgl", "j0qgl", "passZjet && passZmass"+forward+pt030, "QGL", 30, 0, 1 );
//zjetPlots->addTreeVar("zjets_forward040_j0qgl", "j0qgl", "passZjet && passZmass"+forward+pt040, "QGL", 30, 0, 1 );
//zjetPlots->addTreeVar("zjets_forward060_j0qgl", "j0qgl", "passZjet && passZmass"+forward+pt060, "QGL", 30, 0, 1 );
//zjetPlots->addTreeVar("zjets_forward080_j0qgl", "j0qgl", "passZjet && passZmass"+forward+pt080, "QGL", 30, 0, 1 );
//zjetPlots->addTreeVar("zjets_forward120_j0qgl", "j0qgl", "passZjet && passZmass"+forward+pt120, "QGL", 30, 0, 1 );
//zjetPlots->addTreeVar("zjets_forward200_j0qgl", "j0qgl", "passZjet && passZmass"+forward+pt200, "QGL", 30, 0, 1 );

  dijetPlots->addTreeVar("dijets_j0pt" , "j0pt" , dijetselection, "pt_{T} [GeV]", 40, 200, 1000 );
  dijetPlots->addTreeVar("dijets_j0eta", "j0eta", dijetselection, "#eta"        , 30,  -5,    5 );
  dijetPlots->addTreeVar("dijets_rho"  , "rho"  , dijetselection, "#rho"        , 25,   0,   25 );
  dijetPlots->addTreeVar("dijets_npv"  , "npv"  , dijetselection, "npv"         , 34,   1,   34 );
  dijetPlots->addTreeVar("dijets_ht"   , "ht"   , dijetselection, "H_{T} [GeV]" , 50, 450, 1450 );
  dijetPlots->addTreeVar("dijets_central_j0mult"   , "j0mult", dijetselection+central+ptlow, "multiplicity", 35, 0, 70 );
//dijetPlots->addTreeVar("dijets_central020_j0mult", "j0mult", dijetselection+central+pt020, "multiplicity", 35, 0, 70 );
  dijetPlots->addTreeVar("dijets_central030_j0mult", "j0mult", dijetselection+central+pt030, "multiplicity", 35, 0, 70 );
  dijetPlots->addTreeVar("dijets_central040_j0mult", "j0mult", dijetselection+central+pt040, "multiplicity", 35, 0, 70 );
  dijetPlots->addTreeVar("dijets_central060_j0mult", "j0mult", dijetselection+central+pt060, "multiplicity", 35, 0, 70 );
  dijetPlots->addTreeVar("dijets_central080_j0mult", "j0mult", dijetselection+central+pt080, "multiplicity", 35, 0, 70 );
  dijetPlots->addTreeVar("dijets_central120_j0mult", "j0mult", dijetselection+central+pt120, "multiplicity", 35, 0, 70 );
  dijetPlots->addTreeVar("dijets_central200_j0mult", "j0mult", dijetselection+central+pt200, "multiplicity", 35, 0, 70 );
  dijetPlots->addTreeVar("dijets_forward_j0mult"   , "j0mult", dijetselection+forward+ptlow, "multiplicity", 35, 0, 70 );
//dijetPlots->addTreeVar("dijets_forward020_j0mult", "j0mult", dijetselection+forward+pt020, "multiplicity", 35, 0, 70 );
//dijetPlots->addTreeVar("dijets_forward030_j0mult", "j0mult", dijetselection+forward+pt030, "multiplicity", 35, 0, 70 );
//dijetPlots->addTreeVar("dijets_forward040_j0mult", "j0mult", dijetselection+forward+pt040, "multiplicity", 35, 0, 70 );
//dijetPlots->addTreeVar("dijets_forward060_j0mult", "j0mult", dijetselection+forward+pt060, "multiplicity", 35, 0, 70 );
//dijetPlots->addTreeVar("dijets_forward080_j0mult", "j0mult", dijetselection+forward+pt080, "multiplicity", 35, 0, 70 );
//dijetPlots->addTreeVar("dijets_forward120_j0mult", "j0mult", dijetselection+forward+pt120, "multiplicity", 35, 0, 70 );
//dijetPlots->addTreeVar("dijets_forward200_j0mult", "j0mult", dijetselection+forward+pt200, "multiplicity", 35, 0, 70 );
  dijetPlots->addTreeVar("dijets_central_j0ptd"   , "j0ptd", dijetselection+central+ptlow, "ptD", 30, 0, 1 );
//dijetPlots->addTreeVar("dijets_central020_j0ptd", "j0ptd", dijetselection+central+pt020, "ptD", 30, 0, 1 );
  dijetPlots->addTreeVar("dijets_central030_j0ptd", "j0ptd", dijetselection+central+pt030, "ptD", 30, 0, 1 );
  dijetPlots->addTreeVar("dijets_central040_j0ptd", "j0ptd", dijetselection+central+pt040, "ptD", 30, 0, 1 );
  dijetPlots->addTreeVar("dijets_central060_j0ptd", "j0ptd", dijetselection+central+pt060, "ptD", 30, 0, 1 );
  dijetPlots->addTreeVar("dijets_central080_j0ptd", "j0ptd", dijetselection+central+pt080, "ptD", 30, 0, 1 );
  dijetPlots->addTreeVar("dijets_central120_j0ptd", "j0ptd", dijetselection+central+pt120, "ptD", 30, 0, 1 );
  dijetPlots->addTreeVar("dijets_central200_j0ptd", "j0ptd", dijetselection+central+pt200, "ptD", 30, 0, 1 );
  dijetPlots->addTreeVar("dijets_forward_j0ptd"   , "j0ptd", dijetselection+forward+ptlow, "ptD", 30, 0, 1 );
//dijetPlots->addTreeVar("dijets_forward020_j0ptd", "j0ptd", dijetselection+forward+pt020, "ptD", 30, 0, 1 );
//dijetPlots->addTreeVar("dijets_forward030_j0ptd", "j0ptd", dijetselection+forward+pt030, "ptD", 30, 0, 1 );
//dijetPlots->addTreeVar("dijets_forward040_j0ptd", "j0ptd", dijetselection+forward+pt040, "ptD", 30, 0, 1 );
//dijetPlots->addTreeVar("dijets_forward060_j0ptd", "j0ptd", dijetselection+forward+pt060, "ptD", 30, 0, 1 );
//dijetPlots->addTreeVar("dijets_forward080_j0ptd", "j0ptd", dijetselection+forward+pt080, "ptD", 30, 0, 1 );
//dijetPlots->addTreeVar("dijets_forward120_j0ptd", "j0ptd", dijetselection+forward+pt120, "ptD", 30, 0, 1 );
//dijetPlots->addTreeVar("dijets_forward200_j0ptd", "j0ptd", dijetselection+forward+pt200, "ptD", 30, 0, 1 );
  dijetPlots->addTreeVar("dijets_central_j0axis1"   , "j0axis1", dijetselection+central+ptlow, "-Log(axis_{1})", 30, 0, 10 );
//dijetPlots->addTreeVar("dijets_central020_j0axis1", "j0axis1", dijetselection+central+pt020, "-Log(axis_{1})", 30, 0, 10 );
  dijetPlots->addTreeVar("dijets_central030_j0axis1", "j0axis1", dijetselection+central+pt030, "-Log(axis_{1})", 30, 0, 10 );
  dijetPlots->addTreeVar("dijets_central040_j0axis1", "j0axis1", dijetselection+central+pt040, "-Log(axis_{1})", 30, 0, 10 );
  dijetPlots->addTreeVar("dijets_central060_j0axis1", "j0axis1", dijetselection+central+pt060, "-Log(axis_{1})", 30, 0, 10 );
  dijetPlots->addTreeVar("dijets_central080_j0axis1", "j0axis1", dijetselection+central+pt080, "-Log(axis_{1})", 30, 0, 10 );
  dijetPlots->addTreeVar("dijets_central120_j0axis1", "j0axis1", dijetselection+central+pt120, "-Log(axis_{1})", 30, 0, 10 );
  dijetPlots->addTreeVar("dijets_central200_j0axis1", "j0axis1", dijetselection+central+pt200, "-Log(axis_{1})", 30, 0, 10 );
  dijetPlots->addTreeVar("dijets_forward_j0axis1"   , "j0axis1", dijetselection+forward+ptlow, "-Log(axis_{1})", 30, 0, 10 );
//dijetPlots->addTreeVar("dijets_forward020_j0axis1", "j0axis1", dijetselection+forward+pt020, "-Log(axis_{1})", 30, 0, 10 );
//dijetPlots->addTreeVar("dijets_forward030_j0axis1", "j0axis1", dijetselection+forward+pt030, "-Log(axis_{1})", 30, 0, 10 );
//dijetPlots->addTreeVar("dijets_forward040_j0axis1", "j0axis1", dijetselection+forward+pt040, "-Log(axis_{1})", 30, 0, 10 );
//dijetPlots->addTreeVar("dijets_forward060_j0axis1", "j0axis1", dijetselection+forward+pt060, "-Log(axis_{1})", 30, 0, 10 );
//dijetPlots->addTreeVar("dijets_forward080_j0axis1", "j0axis1", dijetselection+forward+pt080, "-Log(axis_{1})", 30, 0, 10 );
//dijetPlots->addTreeVar("dijets_forward120_j0axis1", "j0axis1", dijetselection+forward+pt120, "-Log(axis_{1})", 30, 0, 10 );
//dijetPlots->addTreeVar("dijets_forward200_j0axis1", "j0axis1", dijetselection+forward+pt200, "-Log(axis_{1})", 30, 0, 10 );
  dijetPlots->addTreeVar("dijets_central_j0axis2"   , "j0axis2", dijetselection+central+ptlow, "-Log(axis_{2})", 30, 0, 10 );
//dijetPlots->addTreeVar("dijets_central020_j0axis2", "j0axis2", dijetselection+central+pt020, "-Log(axis_{2})", 30, 0, 10 );
  dijetPlots->addTreeVar("dijets_central030_j0axis2", "j0axis2", dijetselection+central+pt030, "-Log(axis_{2})", 30, 0, 10 );
  dijetPlots->addTreeVar("dijets_central040_j0axis2", "j0axis2", dijetselection+central+pt040, "-Log(axis_{2})", 30, 0, 10 );
  dijetPlots->addTreeVar("dijets_central060_j0axis2", "j0axis2", dijetselection+central+pt060, "-Log(axis_{2})", 30, 0, 10 );
  dijetPlots->addTreeVar("dijets_central080_j0axis2", "j0axis2", dijetselection+central+pt080, "-Log(axis_{2})", 30, 0, 10 );
  dijetPlots->addTreeVar("dijets_central120_j0axis2", "j0axis2", dijetselection+central+pt120, "-Log(axis_{2})", 30, 0, 10 );
  dijetPlots->addTreeVar("dijets_central200_j0axis2", "j0axis2", dijetselection+central+pt200, "-Log(axis_{2})", 30, 0, 10 );
  dijetPlots->addTreeVar("dijets_forward_j0axis2"   , "j0axis2", dijetselection+forward+ptlow, "-Log(axis_{2})", 30, 0, 10 );
//dijetPlots->addTreeVar("dijets_forward020_j0axis2", "j0axis2", dijetselection+forward+pt020, "-Log(axis_{2})", 30, 0, 10 );
//dijetPlots->addTreeVar("dijets_forward030_j0axis2", "j0axis2", dijetselection+forward+pt030, "-Log(axis_{2})", 30, 0, 10 );
//dijetPlots->addTreeVar("dijets_forward040_j0axis2", "j0axis2", dijetselection+forward+pt040, "-Log(axis_{2})", 30, 0, 10 );
//dijetPlots->addTreeVar("dijets_forward060_j0axis2", "j0axis2", dijetselection+forward+pt060, "-Log(axis_{2})", 30, 0, 10 );
//dijetPlots->addTreeVar("dijets_forward080_j0axis2", "j0axis2", dijetselection+forward+pt080, "-Log(axis_{2})", 30, 0, 10 );
//dijetPlots->addTreeVar("dijets_forward120_j0axis2", "j0axis2", dijetselection+forward+pt120, "-Log(axis_{2})", 30, 0, 10 );
//dijetPlots->addTreeVar("dijets_forward200_j0axis2", "j0axis2", dijetselection+forward+pt200, "-Log(axis_{2})", 30, 0, 10 );
  dijetPlots->addTreeVar("dijets_central_j0qgl"   , "j0qgl", dijetselection+central+ptlow, "QGL", 30, 0, 1 );
//dijetPlots->addTreeVar("dijets_central020_j0qgl", "j0qgl", dijetselection+central+pt020, "QGL", 30, 0, 1 );
  dijetPlots->addTreeVar("dijets_central030_j0qgl", "j0qgl", dijetselection+central+pt030, "QGL", 30, 0, 1 );
  dijetPlots->addTreeVar("dijets_central040_j0qgl", "j0qgl", dijetselection+central+pt040, "QGL", 30, 0, 1 );
  dijetPlots->addTreeVar("dijets_central060_j0qgl", "j0qgl", dijetselection+central+pt060, "QGL", 30, 0, 1 );
  dijetPlots->addTreeVar("dijets_central080_j0qgl", "j0qgl", dijetselection+central+pt080, "QGL", 30, 0, 1 );
  dijetPlots->addTreeVar("dijets_central120_j0qgl", "j0qgl", dijetselection+central+pt120, "QGL", 30, 0, 1 );
  dijetPlots->addTreeVar("dijets_central200_j0qgl", "j0qgl", dijetselection+central+pt200, "QGL", 30, 0, 1 );
  dijetPlots->addTreeVar("dijets_forward_j0qgl"   , "j0qgl", dijetselection+forward+ptlow, "QGL", 30, 0, 1 );
//dijetPlots->addTreeVar("dijets_forward020_j0qgl", "j0qgl", dijetselection+forward+pt020, "QGL", 30, 0, 1 );
//dijetPlots->addTreeVar("dijets_forward030_j0qgl", "j0qgl", dijetselection+forward+pt030, "QGL", 30, 0, 1 );
//dijetPlots->addTreeVar("dijets_forward040_j0qgl", "j0qgl", dijetselection+forward+pt040, "QGL", 30, 0, 1 );
//dijetPlots->addTreeVar("dijets_forward060_j0qgl", "j0qgl", dijetselection+forward+pt060, "QGL", 30, 0, 1 );
//dijetPlots->addTreeVar("dijets_forward080_j0qgl", "j0qgl", dijetselection+forward+pt080, "QGL", 30, 0, 1 );
//dijetPlots->addTreeVar("dijets_forward120_j0qgl", "j0qgl", dijetselection+forward+pt120, "QGL", 30, 0, 1 );
//dijetPlots->addTreeVar("dijets_forward200_j0qgl", "j0qgl", dijetselection+forward+pt200, "QGL", 30, 0, 1 );

  gjetPlots->addTreeVar("gjets_j0pt" , "j0pt" , "passGmjet", "pt_{T} [GeV]", 30,  0, 600 );
  gjetPlots->addTreeVar("gjets_j0eta", "j0eta", "passGmjet", "#eta"        , 30, -5,   5 );
  gjetPlots->addTreeVar("gjets_rho"  , "rho"  , "passGmjet", "#rho"        , 25,  0,  25 );
  gjetPlots->addTreeVar("gjets_npv"  , "npv"  , "passGmjet", "npv"         , 34,  1,  35 );
  gjetPlots->addTreeVar("gjets_central_j0mult"   , "j0mult", "passGmjet"+central+ptlow, "multiplicity", 25, 0, 50 );
//gjetPlots->addTreeVar("gjets_central020_j0mult", "j0mult", "passGmjet"+central+pt020, "multiplicity", 25, 0, 50 );
  gjetPlots->addTreeVar("gjets_central030_j0mult", "j0mult", "passGmjet"+central+pt030, "multiplicity", 25, 0, 50 );
  gjetPlots->addTreeVar("gjets_central040_j0mult", "j0mult", "passGmjet"+central+pt040, "multiplicity", 25, 0, 50 );
  gjetPlots->addTreeVar("gjets_central060_j0mult", "j0mult", "passGmjet"+central+pt060, "multiplicity", 25, 0, 50 );
  gjetPlots->addTreeVar("gjets_central080_j0mult", "j0mult", "passGmjet"+central+pt080, "multiplicity", 25, 0, 50 );
  gjetPlots->addTreeVar("gjets_central120_j0mult", "j0mult", "passGmjet"+central+pt120, "multiplicity", 25, 0, 50 );
  gjetPlots->addTreeVar("gjets_central200_j0mult", "j0mult", "passGmjet"+central+pt200, "multiplicity", 25, 0, 50 );
  gjetPlots->addTreeVar("gjets_forward_j0mult"   , "j0mult", "passGmjet"+forward+ptlow, "multiplicity", 25, 0, 50 );
//gjetPlots->addTreeVar("gjets_forward020_j0mult", "j0mult", "passGmjet"+forward+pt020, "multiplicity", 25, 0, 50 );
//gjetPlots->addTreeVar("gjets_forward030_j0mult", "j0mult", "passGmjet"+forward+pt030, "multiplicity", 25, 0, 50 );
//gjetPlots->addTreeVar("gjets_forward040_j0mult", "j0mult", "passGmjet"+forward+pt040, "multiplicity", 25, 0, 50 );
//gjetPlots->addTreeVar("gjets_forward060_j0mult", "j0mult", "passGmjet"+forward+pt060, "multiplicity", 25, 0, 50 );
//gjetPlots->addTreeVar("gjets_forward080_j0mult", "j0mult", "passGmjet"+forward+pt080, "multiplicity", 25, 0, 50 );
//gjetPlots->addTreeVar("gjets_forward120_j0mult", "j0mult", "passGmjet"+forward+pt120, "multiplicity", 25, 0, 50 );
//gjetPlots->addTreeVar("gjets_forward200_j0mult", "j0mult", "passGmjet"+forward+pt200, "multiplicity", 25, 0, 50 );
  gjetPlots->addTreeVar("gjets_central_j0ptd"   , "j0ptd", "passGmjet"+central+ptlow, "ptD", 30, 0, 1 );
//gjetPlots->addTreeVar("gjets_central020_j0ptd", "j0ptd", "passGmjet"+central+pt020, "ptD", 30, 0, 1 );
  gjetPlots->addTreeVar("gjets_central030_j0ptd", "j0ptd", "passGmjet"+central+pt030, "ptD", 30, 0, 1 );
  gjetPlots->addTreeVar("gjets_central040_j0ptd", "j0ptd", "passGmjet"+central+pt040, "ptD", 30, 0, 1 );
  gjetPlots->addTreeVar("gjets_central060_j0ptd", "j0ptd", "passGmjet"+central+pt060, "ptD", 30, 0, 1 );
  gjetPlots->addTreeVar("gjets_central080_j0ptd", "j0ptd", "passGmjet"+central+pt080, "ptD", 30, 0, 1 );
  gjetPlots->addTreeVar("gjets_central120_j0ptd", "j0ptd", "passGmjet"+central+pt120, "ptD", 30, 0, 1 );
  gjetPlots->addTreeVar("gjets_central200_j0ptd", "j0ptd", "passGmjet"+central+pt200, "ptD", 30, 0, 1 );
  gjetPlots->addTreeVar("gjets_forward_j0ptd"   , "j0ptd", "passGmjet"+forward+ptlow, "ptD", 30, 0, 1 );
//gjetPlots->addTreeVar("gjets_forward020_j0ptd", "j0ptd", "passGmjet"+forward+pt020, "ptD", 30, 0, 1 );
//gjetPlots->addTreeVar("gjets_forward030_j0ptd", "j0ptd", "passGmjet"+forward+pt030, "ptD", 30, 0, 1 );
//gjetPlots->addTreeVar("gjets_forward040_j0ptd", "j0ptd", "passGmjet"+forward+pt040, "ptD", 30, 0, 1 );
//gjetPlots->addTreeVar("gjets_forward060_j0ptd", "j0ptd", "passGmjet"+forward+pt060, "ptD", 30, 0, 1 );
//gjetPlots->addTreeVar("gjets_forward080_j0ptd", "j0ptd", "passGmjet"+forward+pt080, "ptD", 30, 0, 1 );
//gjetPlots->addTreeVar("gjets_forward120_j0ptd", "j0ptd", "passGmjet"+forward+pt120, "ptD", 30, 0, 1 );
//gjetPlots->addTreeVar("gjets_forward200_j0ptd", "j0ptd", "passGmjet"+forward+pt200, "ptD", 30, 0, 1 );
  gjetPlots->addTreeVar("gjets_central_j0axis1"   , "j0axis1", "passGmjet"+central+ptlow, "-Log(axis_{1})", 30, 0, 10 );
//gjetPlots->addTreeVar("gjets_central020_j0axis1", "j0axis1", "passGmjet"+central+pt020, "-Log(axis_{1})", 30, 0, 10 );
  gjetPlots->addTreeVar("gjets_central030_j0axis1", "j0axis1", "passGmjet"+central+pt030, "-Log(axis_{1})", 30, 0, 10 );
  gjetPlots->addTreeVar("gjets_central040_j0axis1", "j0axis1", "passGmjet"+central+pt040, "-Log(axis_{1})", 30, 0, 10 );
  gjetPlots->addTreeVar("gjets_central060_j0axis1", "j0axis1", "passGmjet"+central+pt060, "-Log(axis_{1})", 30, 0, 10 );
  gjetPlots->addTreeVar("gjets_central080_j0axis1", "j0axis1", "passGmjet"+central+pt080, "-Log(axis_{1})", 30, 0, 10 );
  gjetPlots->addTreeVar("gjets_central120_j0axis1", "j0axis1", "passGmjet"+central+pt120, "-Log(axis_{1})", 30, 0, 10 );
  gjetPlots->addTreeVar("gjets_central200_j0axis1", "j0axis1", "passGmjet"+central+pt200, "-Log(axis_{1})", 30, 0, 10 );
  gjetPlots->addTreeVar("gjets_forward_j0axis1"   , "j0axis1", "passGmjet"+forward+ptlow, "-Log(axis_{1})", 30, 0, 10 );
//gjetPlots->addTreeVar("gjets_forward020_j0axis1", "j0axis1", "passGmjet"+forward+pt020, "-Log(axis_{1})", 30, 0, 10 );
//gjetPlots->addTreeVar("gjets_forward030_j0axis1", "j0axis1", "passGmjet"+forward+pt030, "-Log(axis_{1})", 30, 0, 10 );
//gjetPlots->addTreeVar("gjets_forward040_j0axis1", "j0axis1", "passGmjet"+forward+pt040, "-Log(axis_{1})", 30, 0, 10 );
//gjetPlots->addTreeVar("gjets_forward060_j0axis1", "j0axis1", "passGmjet"+forward+pt060, "-Log(axis_{1})", 30, 0, 10 );
//gjetPlots->addTreeVar("gjets_forward080_j0axis1", "j0axis1", "passGmjet"+forward+pt080, "-Log(axis_{1})", 30, 0, 10 );
//gjetPlots->addTreeVar("gjets_forward120_j0axis1", "j0axis1", "passGmjet"+forward+pt120, "-Log(axis_{1})", 30, 0, 10 );
//gjetPlots->addTreeVar("gjets_forward200_j0axis1", "j0axis1", "passGmjet"+forward+pt200, "-Log(axis_{1})", 30, 0, 10 );
  gjetPlots->addTreeVar("gjets_central_j0axis2"   , "j0axis2", "passGmjet"+central+ptlow, "-Log(axis_{2})", 30, 0, 10 );
//gjetPlots->addTreeVar("gjets_central020_j0axis2", "j0axis2", "passGmjet"+central+pt020, "-Log(axis_{2})", 30, 0, 10 );
  gjetPlots->addTreeVar("gjets_central030_j0axis2", "j0axis2", "passGmjet"+central+pt030, "-Log(axis_{2})", 30, 0, 10 );
  gjetPlots->addTreeVar("gjets_central040_j0axis2", "j0axis2", "passGmjet"+central+pt040, "-Log(axis_{2})", 30, 0, 10 );
  gjetPlots->addTreeVar("gjets_central060_j0axis2", "j0axis2", "passGmjet"+central+pt060, "-Log(axis_{2})", 30, 0, 10 );
  gjetPlots->addTreeVar("gjets_central080_j0axis2", "j0axis2", "passGmjet"+central+pt080, "-Log(axis_{2})", 30, 0, 10 );
  gjetPlots->addTreeVar("gjets_central120_j0axis2", "j0axis2", "passGmjet"+central+pt120, "-Log(axis_{2})", 30, 0, 10 );
  gjetPlots->addTreeVar("gjets_central200_j0axis2", "j0axis2", "passGmjet"+central+pt200, "-Log(axis_{2})", 30, 0, 10 );
  gjetPlots->addTreeVar("gjets_forward_j0axis2"   , "j0axis2", "passGmjet"+forward+ptlow, "-Log(axis_{2})", 30, 0, 10 );
//gjetPlots->addTreeVar("gjets_forward020_j0axis2", "j0axis2", "passGmjet"+forward+pt020, "-Log(axis_{2})", 30, 0, 10 );
//gjetPlots->addTreeVar("gjets_forward030_j0axis2", "j0axis2", "passGmjet"+forward+pt030, "-Log(axis_{2})", 30, 0, 10 );
//gjetPlots->addTreeVar("gjets_forward040_j0axis2", "j0axis2", "passGmjet"+forward+pt040, "-Log(axis_{2})", 30, 0, 10 );
//gjetPlots->addTreeVar("gjets_forward060_j0axis2", "j0axis2", "passGmjet"+forward+pt060, "-Log(axis_{2})", 30, 0, 10 );
//gjetPlots->addTreeVar("gjets_forward080_j0axis2", "j0axis2", "passGmjet"+forward+pt080, "-Log(axis_{2})", 30, 0, 10 );
//gjetPlots->addTreeVar("gjets_forward120_j0axis2", "j0axis2", "passGmjet"+forward+pt120, "-Log(axis_{2})", 30, 0, 10 );
//gjetPlots->addTreeVar("gjets_forward200_j0axis2", "j0axis2", "passGmjet"+forward+pt200, "-Log(axis_{2})", 30, 0, 10 );
  gjetPlots->addTreeVar("gjets_central_j0qgl"   , "j0qgl", "passGmjet"+central+ptlow, "QGL", 30, 0, 1 );
//gjetPlots->addTreeVar("gjets_central020_j0qgl", "j0qgl", "passGmjet"+central+pt020, "QGL", 30, 0, 1 );
  gjetPlots->addTreeVar("gjets_central030_j0qgl", "j0qgl", "passGmjet"+central+pt030, "QGL", 30, 0, 1 );
  gjetPlots->addTreeVar("gjets_central040_j0qgl", "j0qgl", "passGmjet"+central+pt040, "QGL", 30, 0, 1 );
  gjetPlots->addTreeVar("gjets_central060_j0qgl", "j0qgl", "passGmjet"+central+pt060, "QGL", 30, 0, 1 );
  gjetPlots->addTreeVar("gjets_central080_j0qgl", "j0qgl", "passGmjet"+central+pt080, "QGL", 30, 0, 1 );
  gjetPlots->addTreeVar("gjets_central120_j0qgl", "j0qgl", "passGmjet"+central+pt120, "QGL", 30, 0, 1 );
  gjetPlots->addTreeVar("gjets_central200_j0qgl", "j0qgl", "passGmjet"+central+pt200, "QGL", 30, 0, 1 );
  gjetPlots->addTreeVar("gjets_forward_j0qgl"   , "j0qgl", "passGmjet"+forward+ptlow, "QGL", 30, 0, 1 );
//gjetPlots->addTreeVar("gjets_forward020_j0qgl", "j0qgl", "passGmjet"+forward+pt020, "QGL", 30, 0, 1 );
//gjetPlots->addTreeVar("gjets_forward030_j0qgl", "j0qgl", "passGmjet"+forward+pt030, "QGL", 30, 0, 1 );
//gjetPlots->addTreeVar("gjets_forward040_j0qgl", "j0qgl", "passGmjet"+forward+pt040, "QGL", 30, 0, 1 );
//gjetPlots->addTreeVar("gjets_forward060_j0qgl", "j0qgl", "passGmjet"+forward+pt060, "QGL", 30, 0, 1 );
//gjetPlots->addTreeVar("gjets_forward080_j0qgl", "j0qgl", "passGmjet"+forward+pt080, "QGL", 30, 0, 1 );
//gjetPlots->addTreeVar("gjets_forward120_j0qgl", "j0qgl", "passGmjet"+forward+pt120, "QGL", 30, 0, 1 );
//gjetPlots->addTreeVar("gjets_forward200_j0qgl", "j0qgl", "passGmjet"+forward+pt200, "QGL", 30, 0, 1 );

  zjetPlots   ->plot();
  dijetPlots  ->plot();
  gjetPlots   ->plot();

  delete zjetPlots;
  delete dijetPlots;
  delete gjetPlots;

}
